language: go

go:
  - tip

addons:
  - postgresql : "9.3"

install:
  - go get -t -v ./...
  - go get golang.org/x/tools/cmd/cover

script:
  - export POSTGRES_URL="postgres://postgres@localhost:5432?sslmode=disable"
  - go test -cover ./...

notifications:
  - email: false
